version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - '28001:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S0meVeryHardPassword
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'S0meVeryHardPassword' -Q 'SELECT 1'
  waitmssql:
    image: microsoft/mssql-server-linux:latest
    links:
      - mssql
    depends_on:
      - mssql
    entrypoint:
      - bash
      - -c
      - 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P S0meVeryHardPassword -d master -Q "CREATE DATABASE knex_test"; do sleep 5; done'

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '28002:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=testrootpassword
      - MYSQL_DATABASE=knex_test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    healthcheck:
      test: /usr/bin/mysql -hlocalhost -utestuser -ptestpassword -e 'SELECT 1'
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
  waitmysql:
    image: mysql
    links:
      - mysql
    depends_on:
      - mysql
    entrypoint:
      - bash
      - -c
      - 'until /usr/bin/mysql -hmysql -utestuser -ptestpassword -e "SELECT 1"; do sleep 5; done'

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '28003:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=testrootpassword
      - MYSQL_DATABASE=knex_test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    healthcheck:
      test: /usr/bin/mysql -hlocalhost -utestuser -ptestpassword -e 'SELECT 1'
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
  waitmariadb:
    image: mariadb
    links:
      - mariadb
    depends_on:
      - mariadb
    entrypoint:
      - bash
      - -c
      - 'until /usr/bin/mysql -hmariadb -utestuser -ptestpassword -e "SELECT 1"; do sleep 5; done'

  postgres:
    image: postgres:alpine
    ports:
      - '28004:5432'
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=knex_test
  waitpostgres:
    image: postgres:alpine
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://testuser:testpassword@postgres/knex_test -c "SELECT 1"; do sleep 5; done'
